language: python
sudo: false

python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install tox-travis

# command to run tests
script: tox

after_success:
  - codecov

os:
  - linux

cache:
  directories:
  - $HOME/.cache/pip