name: github pages

on:
  push:
    branches:
      - master
#    paths:
#      - "docs/**"
#      - "tools/**/README.md"
#      - "tools/**/META"

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1  # v2 does not have submodules option now

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.66.0'
          extended: true

      - name: Build Doc
        run: python3 build_doc.py

      - name: Jekyll Build
        uses: gha-utilities/jekyll-build@v0.0.3
        with:
          source: ./docs
          destination: ./docs/_site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ~/docs/_site
          keep_files: false