name: Build Docker Images

on:
  push:
    branches:
      - master
    paths:
      - "tools/package-manager/**"

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1  # v2 does not have submodules option now

      - name: Build images
        run: python3 build_docker_images.py | sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}